using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidad
{
    public class Efectividad
    {
        public int IdEfectividad { get; set; }
        public DateTime FechaEvaluacion { get; set; }
        public decimal EneroPrestamos { get; set; }
        public decimal EneroRecuperacion { get; set; }
        public decimal EneroMorosidad { get; set; }
        public decimal EneroDepositos { get; set; }
        public decimal EneroAportaciones { get; set; }
        public decimal EneroRentabilidad { get; set; }
        public decimal EneroTotalActivos { get; set; }
        public decimal EneroTotal { get; set; }
        public decimal EneroCalificacion { get; set; }
        public string EneroStatus { get; set; }
        public decimal EneroAumento { get; set; }
        public decimal FebreroPrestamos { get; set; }
        public decimal FebreroRecuperacion { get; set; }
        public decimal FebreroMorosidad { get; set; }
        public decimal FebreroDepositos { get; set; }
        public decimal FebreroAportaciones { get; set; }
        public decimal FebreroRentabilidad { get; set; }
        public decimal FebreroTotalActivos { get; set; }
        public decimal FebreroTotal { get; set; }
        public decimal FebreroCalificacion { get; set; }
        public string FebreroStatus { get; set; }
        public decimal FebreroAumento { get; set; }
        public decimal MarzoPrestamos { get; set; }
        public decimal MarzoRecuperacion { get; set; }
        public decimal MarzoMorosidad { get; set; }
        public decimal MarzoDepositos { get; set; }
        public decimal MarzoAportaciones { get; set; }
        public decimal MarzoRentabilidad { get; set; }
        public decimal MarzoTotalActivos { get; set; }
        public decimal MarzoTotal { get; set; }
        public decimal MarzoCalificacion { get; set; }
        public string MarzoStatus { get; set; }
        public decimal MarzoAumento { get; set; }
        public decimal AbrilPrestamos { get; set; }
        public decimal AbrilRecuperacion { get; set; }
        public decimal AbrilMorosidad { get; set; }
        public decimal AbrilDepositos { get; set; }
        public decimal AbrilAportaciones { get; set; }
        public decimal AbrilRentabilidad { get; set; }
        public decimal AbrilTotalActivos { get; set; }
        public decimal AbrilTotal { get; set; }
        public decimal AbrilCalificacion { get; set; }
        public string AbrilStatus { get; set; }
        public decimal AbrilAumento { get; set; }
        public decimal MayoPrestamos { get; set; }
        public decimal MayoRecuperacion { get; set; }
        public decimal MayoMorosidad { get; set; }
        public decimal MayoDepositos { get; set; }
        public decimal MayoAportaciones { get; set; }
        public decimal MayoRentabilidad { get; set; }
        public decimal MayoTotalActivos { get; set; }
        public decimal MayoTotal { get; set; }
        public decimal MayoCalificacion { get; set; }
        public string MayoStatus { get; set; }
        public decimal MayoAumento { get; set; }
        public decimal JunioPrestamos { get; set; }
        public decimal JunioRecuperacion { get; set; }
        public decimal JunioMorosidad { get; set; }
        public decimal JunioDepositos { get; set; }
        public decimal JunioAportaciones { get; set; }
        public decimal JunioRentabilidad { get; set; }
        public decimal JunioTotalActivos { get; set; }
        public decimal JunioTotal { get; set; }
        public decimal JunioCalificacion { get; set; }
        public string JunioStatus { get; set; }
        public decimal JunioAumento { get; set; }
        public decimal JulioPrestamos { get; set; }
        public decimal JulioRecuperacion { get; set; }
        public decimal JulioMorosidad { get; set; }
        public decimal JulioDepositos { get; set; }
        public decimal JulioAportaciones { get; set; }
        public decimal JulioRentabilidad { get; set; }
        public decimal JulioTotalActivos { get; set; }
        public decimal JulioTotal { get; set; }
        public decimal JulioCalificacion { get; set; }
        public string JulioStatus { get; set; }
        public decimal JulioAumento { get; set; }
        public decimal AgostoPrestamos { get; set; }
        public decimal AgostoRecuperacion { get; set; }
        public decimal AgostoMorosidad { get; set; }
        public decimal AgostoDepositos { get; set; }
        public decimal AgostoAportaciones { get; set; }
        public decimal AgostoRentabilidad { get; set; }
        public decimal AgostoTotalActivos { get; set; }
        public decimal AgostoTotal { get; set; }
        public decimal AgostoCalificacion { get; set; }
        public string AgostoStatus { get; set; }
        public decimal AgostoAumento { get; set; }
        public decimal SeptiembrePrestamos { get; set; }
        public decimal SeptiembreRecuperacion { get; set; }
        public decimal SeptiembreMorosidad { get; set; }
        public decimal SeptiembreDepositos { get; set; }
        public decimal SeptiembreAportaciones { get; set; }
        public decimal SeptiembreRentabilidad { get; set; }
        public decimal SeptiembreTotalActivos { get; set; }
        public decimal SeptiembreTotal { get; set; }
        public decimal SeptiembreCalificacion { get; set; }
        public string SeptiembreStatus { get; set; }
        public decimal SeptiembreAumento { get; set; }
        public decimal OctubrePrestamos { get; set; }
        public decimal OctubreRecuperacion { get; set; }
        public decimal OctubreMorosidad { get; set; }
        public decimal OctubreDepositos { get; set; }
        public decimal OctubreAportaciones { get; set; }
        public decimal OctubreRentabilidad { get; set; }
        public decimal OctubreTotalActivos { get; set; }
        public decimal OctubreTotal { get; set; }
        public decimal OctubreCalificacion { get; set; }
        public string OctubreStatus { get; set; }
        public decimal OctubreAumento { get; set; }
        public decimal NoviembrePrestamos { get; set; }
        public decimal NoviembreRecuperacion { get; set; }
        public decimal NoviembreMorosidad { get; set; }
        public decimal NoviembreDepositos { get; set; }
        public decimal NoviembreAportaciones { get; set; }
        public decimal NoviembreRentabilidad { get; set; }
        public decimal NoviembreTotalActivos { get; set; }
        public decimal NoviembreTotal { get; set; }
        public decimal NoviembreCalificacion { get; set; }
        public string NoviembreStatus { get; set; }
        public decimal NoviembreAumento { get; set; }
        public decimal DiciembrePrestamos { get; set; }
        public decimal DiciembreRecuperacion { get; set; }
        public decimal DiciembreMorosidad { get; set; }
        public decimal DiciembreDepositos { get; set; }
        public decimal DiciembreAportaciones { get; set; }
        public decimal DiciembreRentabilidad { get; set; }
        public decimal DiciembreTotalActivos { get; set; }
        public decimal DiciembreTotal { get; set; }
        public decimal DiciembreCalificacion { get; set; }
        public string DiciembreStatus { get; set; }
        public decimal DiciembreAumento { get; set; }
        public decimal EfectividadPrestamos { get; set; }
        public decimal EfectividadRecuperacion { get; set; }
        public decimal EfectividadMorosidad { get; set; }
        public decimal EfectividadDepositos { get; set; }
        public decimal EfectividadAportaciones { get; set; }
        public decimal EfectividadRentabilidad { get; set; }
        public decimal EfectividadTotalActivos { get; set; }
        public decimal EfectividadTotal { get; set; }
        public decimal EfectividadCalificacion { get; set; }
        public string EfectividadStatus { get; set; }
        public decimal EfectividadAumento { get; set; }
        public Usuario oUsuario { get; set; }
        public DateTime FechaRegistro { get; set; }
    }
}
