using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidad
{
    public class Financieros
    {
        public int IdFinancieros { get; set; }
        public DateTime FechaAl { get; set; }
        public decimal IngresosFinancieros { get; set; }
        public decimal IngresosPrestamos { get; set; }
        public decimal IngresosInverLiquidas { get; set; }
        public decimal IngresosInverFinan { get; set; }
        public decimal IngresosNoFinancieros { get; set; }
        public decimal IngresosInverNoFinan { get; set; }
        public decimal OtrosIngresos { get; set; }
        public decimal IngresosOtrasFuentes { get; set; }
        public decimal IngresosExtraordinarios { get; set; }
        public decimal TotalIngresos { get; set; }
        public decimal CostosFinancieros { get; set; }
        public decimal CostosFinanAhorros { get; set; }
        public decimal CostosFinanCreExterno { get; set; }
        public decimal CostosFinanAportaciones { get; set; }
        public decimal OtrosCostosFinancieros { get; set; }
        public decimal MargenBruto { get; set; }
        public decimal GastosOperativos { get; set; }
        public decimal ProvisionActivosRiesgo { get; set; }
        public decimal UtilidadOperaciones { get; set; }
        public decimal OtrosIngresosGastos { get; set; }
        public decimal IngresosExtra { get; set; }
        public decimal RectificaAniosAnter { get; set; }
        public decimal Impuestos { get; set; }
        public decimal ResultadoEjercicio { get; set; }
        public decimal GastosPersonal { get; set; }
        public decimal SueldosSalarios { get; set; }
        public decimal PrestacionesLaborales { get; set; }
        public decimal CuotasPatronales { get; set; }
        public decimal IncentivosBonos { get; set; }
        public decimal SegurosFianzas { get; set; }
        public decimal CapacitacionEducacion { get; set; }
        public decimal ViaticosTransportes { get; set; }
        public decimal Gobernabilidad { get; set; }
        public decimal Dietas { get; set; }
        public decimal ViaticosGobernanza { get; set; }
        public decimal SegurosGobernanza { get; set; }
        public decimal GastosAsamblea { get; set; }
        public decimal AuditoriaSupervision { get; set; }
        public decimal CapacitacionGobernanza { get; set; }
        public decimal OtrosGobernanza { get; set; }
        public decimal Mercadeo { get; set; }
        public decimal Ahorros { get; set; }
        public decimal Prestamos { get; set; }
        public decimal Asociados { get; set; }
        public decimal EstudioMercado { get; set; }
        public decimal NuevosProductos { get; set; }
        public decimal ApoyoSocial { get; set; }
        public decimal OtrosGtosMercadeo { get; set; }
        public decimal Administracion { get; set; }
        public decimal ReunionesColaboradores { get; set; }
        public decimal HonoraProfesionales { get; set; }
        public decimal SeguridadProteccion { get; set; }
        public decimal PapeleriaUtiles { get; set; }
        public decimal Combustibles { get; set; }
        public decimal ReparaMantenimiento { get; set; }
        public decimal Arrendamientos { get; set; }
        public decimal AguaEnergia { get; set; }
        public decimal Comunicaciones { get; set; }
        public decimal PasajesFletes { get; set; }
        public decimal ImpuestosContrib { get; set; }
        public decimal OtrosGtosAdmon { get; set; }
        public decimal Depreciaciones { get; set; }
        public decimal DepreciacionesValor { get; set; }
        public decimal TotalGtosOperativos { get; set; }
        public decimal ActivoProductivo { get; set; }
        public decimal Disponibilidades { get; set; }
        public decimal EncajeCooperativo { get; set; }
        public decimal DepositosMonetarios { get; set; }
        public decimal DepositosAhorro { get; set; }
        public decimal OperaIntersistema { get; set; }
        public decimal DepositosPlazoFijo { get; set; }
        public decimal RemesasFamiliares { get; set; }
        public decimal EstimAcumInverLiquidas { get; set; }
        public decimal PrestamosAsociados { get; set; }
        public decimal PrestamosCorrientes { get; set; }
        public decimal PrestamosRiesgo { get; set; }
        public decimal PrestamosJuicio { get; set; }
        public decimal OtrosPrestamos { get; set; }
        public decimal EstimAcumPtmos { get; set; }
        public decimal InversionesFinancieras { get; set; }
        public decimal AportaParticipaciones { get; set; }
        public decimal OtrasInverFinancieras { get; set; }
        public decimal FondoRespaldo { get; set; }
        public decimal FondoConsultas { get; set; }
        public decimal InversionesAgencias { get; set; }
        public decimal EstimAcumInverFinan { get; set; }
        public decimal InversionesNoFinan { get; set; }
        public decimal InverNoFinancieras { get; set; }
        public decimal EstimAcumInverNoFinan { get; set; }
        public decimal ActivoImproductivo { get; set; }
        public decimal ActivosLiquidos { get; set; }
        public decimal DisponibilidadCaja { get; set; }
        public decimal DepoMonetarios { get; set; }
        public decimal OtrosActivosLiquidos { get; set; }
        public decimal CuentasPorCobrar { get; set; }
        public decimal CtasPorCobrar { get; set; }
        public decimal DeudoresVarios { get; set; }
        public decimal InteresesPorCobrar { get; set; }
        public decimal OtrasCtasPorCobrar { get; set; }
        public decimal EstimAcumCtasPorCobrar { get; set; }
        public decimal BienesLiquidacion { get; set; }
        public decimal ActivosExtraordinarios { get; set; }
        public decimal EstimAcumBienesLiquida { get; set; }
        public decimal ActivosFijos { get; set; }
        public decimal Terrenos { get; set; }
        public decimal Edificios { get; set; }
        public decimal DepAcumEdificios { get; set; }
        public decimal Instalaciones { get; set; }
        public decimal DepAcumInstalaciones { get; set; }
        public decimal EquipoComputo { get; set; }
        public decimal DepAcumEquipoComputo { get; set; }
        public decimal MueblesEquipo { get; set; }
        public decimal DepAcumMueblesEquipo { get; set; }
        public decimal Vehiculos { get; set; }
        public decimal DepAcumVehiculos { get; set; }
        public decimal ActivosDiferidos { get; set; }
        public decimal GastosOrganizacion { get; set; }
        public decimal GastosAnticipados { get; set; }
        public decimal OtrosGtosDiferidos { get; set; }
        public decimal CuentaCorriente { get; set; }
        public decimal EstimAcumActivosDiferidos { get; set; }
        public decimal OtrosActivos { get; set; }
        public decimal ActivosValorDudoso { get; set; }
        public decimal DiscrepanciaContable { get; set; }
        public decimal ActivosRiesgo { get; set; }
        public decimal EstimAcumActivosRiesgo { get; set; }
        public decimal TotalActivos { get; set; }
        public decimal PasivoConCosto { get; set; }
        public decimal AhorrosAsociados { get; set; }
        public decimal AhorroCorriente { get; set; }
        public decimal AhorroPlazoFijo { get; set; }
        public decimal AhorroInfantoJuvenil { get; set; }
        public decimal AhorroProgramado { get; set; }
        public decimal AhorroFemenino { get; set; }
        public decimal OtrosAhorros { get; set; }
        public decimal PasivoLargoPlazo { get; set; }
        public decimal CtasPorPagar { get; set; }
        public decimal CreditosSubordinados { get; set; }
        public decimal CapitalSemilla { get; set; }
        public decimal FondoRespaldoPasivo { get; set; }
        public decimal OtrosCreditos { get; set; }
        public decimal CuentaCorrientePasivo { get; set; }
        public decimal PasivoSinCosto { get; set; }
        public decimal ObligaInmediatas { get; set; }
        public decimal ObligaLargoPlazo { get; set; }
        public decimal Provisiones { get; set; }
        public decimal OtrosPasivos { get; set; }
        public decimal PasivoTotal { get; set; }
        public decimal CapitalContable { get; set; }
        public decimal CapitalSocial { get; set; }
        public decimal AportacionesObligatorias { get; set; }
        public decimal AportacionesVoluntarias { get; set; }
        public decimal AportacionesInfantiles { get; set; }
        public decimal OtrasAportaciones { get; set; }
        public decimal CapitalInstitucional { get; set; }
        public decimal ReservasInstitucionales { get; set; }
        public decimal ResultadosAcumulados { get; set; }
        public decimal CapitalSubordinado { get; set; }
        public decimal Donaciones { get; set; }
        public decimal Resultado { get; set; }
        public decimal TotalPasivoCapital { get; set; }
        public int TotalUsuarios { get; set; }
        public int UsuariosActivos { get; set; }
        public int UsuariosPrestamos { get; set; }
        public int UsuariosACorriente { get; set; }
        public int UsuariosPlazoFijo { get; set; }
        public int UsuariosOtrosServicios { get; set; }
        public int AsociadosTotal { get; set; }
        public int AsociadosMujeres { get; set; }
        public int AsociadosHombres { get; set; }
        public int AsociadosOtros { get; set; }
        public int TotalColaboradores { get; set; }
        public int ColaboraMujeres { get; set; }
        public int ColaboraHombres { get; set; }
        public decimal ComportamientoMercado { get; set; }
        public int CaptacionMercado { get; set; }
        public int PoblacionMercado { get; set; }
        public Usuario oUsuario { get; set; }
        public DateTime FechaRegistro { get; set; }        
    }
}
