using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidad
{
    public class Operativos
    {
        public int IdOperativos { get; set; }
        public DateTime FechaProyeccion { get; set; }
        public decimal PatronalesDirectivos { get; set; }
        public decimal IncentivosDirectivos { get; set; }
        public decimal TotalDirectivos { get; set; }
        public decimal SueldosGerencia { get; set; }
        public decimal PrestacionesGerencia { get; set; }
        public decimal PatronalesGerencia { get; set; }
        public decimal IncentivosGerencia { get; set; }
        public decimal SegurosGerencia { get; set; }
        public decimal CapacitacionGerencia { get; set; }
        public decimal ViaticosGerencia { get; set; }
        public decimal TotalGerencia { get; set; }
        public decimal SueldosFinanzas { get; set; }
        public decimal PrestacionesFinanzas { get; set; }
        public decimal PatronalesFinanzas { get; set; }
        public decimal IncentivosFinanzas { get; set; }
        public decimal SegurosFinanzas { get; set; }
        public decimal CapacitacionFinanzas { get; set; }
        public decimal ViaticosFinanzas { get; set; }
        public decimal TotalFinanzas { get; set; }
        public decimal SueldosConta { get; set; }
        public decimal PrestacionesConta { get; set; }
        public decimal PatronalesConta { get; set; }
        public decimal IncentivosConta { get; set; }
        public decimal SegurosConta { get; set; }
        public decimal CapacitacionConta { get; set; }
        public decimal ViaticosConta { get; set; }
        public decimal TotalConta { get; set; }
        public decimal SueldosRHumanos { get; set; }
        public decimal PrestacionesRHumanos { get; set; }
        public decimal PatronalesRHumanos { get; set; }
        public decimal IncentivosRHumanos { get; set; }
        public decimal SegurosRHumanos { get; set; }
        public decimal CapacitacionRHumanos { get; set; }
        public decimal ViaticosRHumanos { get; set; }
        public decimal TotalRHumanos { get; set; }
        public decimal SueldosCaja { get; set; }
        public decimal PrestacionesCaja { get; set; }
        public decimal PatronalesCaja { get; set; }
        public decimal IncentivosCaja { get; set; }
        public decimal SegurosCaja { get; set; }
        public decimal CapacitacionCaja { get; set; }
        public decimal ViaticosCaja { get; set; }
        public decimal TotalCaja { get; set; }
        public decimal SueldosCreditos { get; set; }
        public decimal PrestacionesCreditos { get; set; }
        public decimal PatronalesCreditos { get; set; }
        public decimal IncentivosCreditos { get; set; }
        public decimal SegurosCreditos { get; set; }
        public decimal CapacitacionCreditos { get; set; }
        public decimal ViaticosCreditos { get; set; }
        public decimal TotalCreditos { get; set; }
        public decimal SueldosInformatica { get; set; }
        public decimal PrestacionesInformatica { get; set; }
        public decimal PatronalesInformatica { get; set; }
        public decimal IncentivosInformatica { get; set; }
        public decimal SegurosInformatica { get; set; }
        public decimal CapacitacionInformatica { get; set; }
        public decimal ViaticosInformatica { get; set; }
        public decimal TotalInformatica { get; set; }
        public decimal SueldosCobranza { get; set; }
        public decimal PrestacionesCobranza { get; set; }
        public decimal PatronalesCobranza { get; set; }
        public decimal IncentivosCobranza { get; set; }
        public decimal SegurosCobranza { get; set; }
        public decimal CapacitacionCobranza { get; set; }
        public decimal ViaticosCobranza { get; set; }
        public decimal TotalCobranza { get; set; }
        public decimal SueldosMercadeo { get; set; }
        public decimal PrestacionesMercadeo { get; set; }
        public decimal PatronalesMercadeo { get; set; }
        public decimal IncentivosMercadeo { get; set; }
        public decimal SegurosMercadeo { get; set; }
        public decimal CapacitacionMercadeo { get; set; }
        public decimal ViaticosMercadeo { get; set; }
        public decimal TotalMercadeo { get; set; }
        public decimal SueldosNegocios { get; set; }
        public decimal PrestacionesNegocios { get; set; }
        public decimal PatronalesNegocios { get; set; }
        public decimal IncentivosNegocios { get; set; }
        public decimal SegurosNegocios { get; set; }
        public decimal CapacitacionNegocios { get; set; }
        public decimal ViaticosNegocios { get; set; }
        public decimal TotalNegocios { get; set; }
        public decimal SueldosAgencias { get; set; }
        public decimal PrestacionesAgencias { get; set; }
        public decimal PatronalesAgencias { get; set; }
        public decimal IncentivosAgencias { get; set; }
        public decimal SegurosAgencias { get; set; }
        public decimal CapacitacionAgencias { get; set; }
        public decimal ViaticosAgencias { get; set; }
        public decimal TotalAgencias { get; set; }
        public decimal SueldosTotal { get; set; }
        public decimal PrestacionesTotal { get; set; }
        public decimal PatronalesTotal { get; set; }
        public decimal IncentivosTotal { get; set; }
        public decimal SegurosTotal { get; set; }
        public decimal CapacitacionTotal { get; set; }
        public decimal ViaticosTotal { get; set; }
        public decimal TotalTotal { get; set; }
        public decimal DietasDirectivos { get; set; }
        public decimal ViaticosDirectivos { get; set; }
        public decimal SegurosDirectivos { get; set; }
        public decimal AsambleaDirectivos { get; set; }
        public decimal AuditoriaDirectivos { get; set; }
        public decimal CapacitacionDirectivos { get; set; }
        public decimal OtrosDirectivos { get; set; }
        public decimal TotalGtosDirectivos { get; set; }
        public decimal DietasAgenciasDirectivos { get; set; }
        public decimal ViaticosAgenciasDirectivos { get; set; }
        public decimal SegurosAgenciasDirectivos { get; set; }
        public decimal AsambleaAgenciasDirectivos { get; set; }
        public decimal AuditoriaAgenciasDirectivos { get; set; }
        public decimal CapacitacionAgenciasDirectivos { get; set; }
        public decimal OtrosAgenciasDirectivos { get; set; }
        public decimal TotalAgenciasDirectivos { get; set; }
        public decimal DietasTotalDirectivos { get; set; }
        public decimal ViaticosTotalDirectivos { get; set; }
        public decimal SegurosTotalDirectivos { get; set; }
        public decimal AsambleaTotalDirectivos { get; set; }
        public decimal AuditoriaTotalDirectivos { get; set; }
        public decimal CapacitacionTotalDirectivos { get; set; }
        public decimal OtrosTotalDirectivos { get; set; }
        public decimal TotalTotalDirectivos { get; set; }
        public decimal AhorrosMercadeo { get; set; }
        public decimal PrestamosMercadeo { get; set; }
        public decimal AsociadosMercadeo { get; set; }
        public decimal EstudioMercadeo { get; set; }
        public decimal DesarrolloMercadeo { get; set; }
        public decimal ApoyoMercadeo { get; set; }
        public decimal OtrosGtosMercadeo { get; set; }
        public decimal TotalGastosMercadeo { get; set; }
        public decimal AhorrosMercaAgencias { get; set; }
        public decimal PrestamosMercaAgencias { get; set; }
        public decimal AsociadosMercaAgencias { get; set; }
        public decimal EstudioMercaAgencias { get; set; }
        public decimal DesarrolloMercaAgencias { get; set; }
        public decimal ApoyoMercaAgencias { get; set; }
        public decimal OtrosMercaAgencias { get; set; }
        public decimal TotalMercaAgencias { get; set; }
        public decimal AhorrosMercaTotal { get; set; }
        public decimal PrestamosMercaTotal { get; set; }
        public decimal AsociadosMercaTotal { get; set; }
        public decimal EstudioMercaTotal { get; set; }
        public decimal DesarrolloMercaTotal { get; set; }
        public decimal ApoyoMercaTotal { get; set; }
        public decimal OtrosMercaTotal { get; set; }
        public decimal TotalTotalMercadeo { get; set; }
        public decimal ReunionesAdmon { get; set; }
        public decimal HonorariosAdmon { get; set; }
        public decimal SeguridadAdmon { get; set; }
        public decimal PapeleriaAdmon { get; set; }
        public decimal CombustibleAdmon { get; set; }
        public decimal ReparacionesAdmon { get; set; }
        public decimal ArrendamientosAdmon { get; set; }
        public decimal EnergiaAdmon { get; set; }
        public decimal ComunicacionesAdmon { get; set; }
        public decimal PasajesAdmon { get; set; }
        public decimal ImpuestosAdmon { get; set; }
        public decimal OtrosAdmon { get; set; }
        public decimal TotalAdmon { get; set; }
        public decimal ReunionesAdmonAgencias { get; set; }
        public decimal HonorariosAdmonAgencias { get; set; }
        public decimal SeguridadAdmonAgencias { get; set; }
        public decimal PapeleriaAdmonAgencias { get; set; }
        public decimal CombustibleAdmonAgencias { get; set; }
        public decimal ReparacionesAdmonAgencias { get; set; }
        public decimal ArrendamientosAdmonAgencias { get; set; }
        public decimal EnergiaAdmonAgencias { get; set; }
        public decimal ComunicacionesAdmonAgencias { get; set; }
        public decimal PasajesAdmonAgencias { get; set; }
        public decimal ImpuestosAdmonAgencias { get; set; }
        public decimal OtrosAdmonAgencias { get; set; }
        public decimal TotalAdmonAgencias { get; set; }
        public decimal ReunionesTotal { get; set; }
        public decimal HonorariosTotal { get; set; }
        public decimal SeguridadTotal { get; set; }
        public decimal PapeleriaTotal { get; set; }
        public decimal CombustibleTotal { get; set; }
        public decimal ReparacionesTotal { get; set; }
        public decimal ArrendamientosTotal { get; set; }
        public decimal EnergiaTotal { get; set; }
        public decimal ComunicacionesTotal { get; set; }
        public decimal PasajesTotal { get; set; }
        public decimal ImpuestosTotal { get; set; }
        public decimal OtrosAdmonTotal { get; set; }
        public decimal TotalTotalAdmon { get; set; }
        public decimal Depreciaciones { get; set; }
        public decimal TotalDepreciaciones { get; set; }
        public decimal DepreciacionesAgencias { get; set; }
        public decimal TotalDepreAgencias { get; set; }
        public decimal TotalGtosDepreciaciones { get; set; }
        public decimal TotalDepreciacionesTotal { get; set; }
        public decimal TotalDirectivosTotal { get; set; }
        public decimal TotalGerenciaTotal { get; set; }
        public decimal TotalFinanzasTotal { get; set; }
        public decimal TotalContaTotal { get; set; }
        public decimal TotalRHumanosTotal { get; set; }
        public decimal TotalCajaTotal { get; set; }
        public decimal TotalCreditosTotal { get; set; }
        public decimal TotalInformaticaTotal { get; set; }
        public decimal TotalCobranzaTotal { get; set; }
        public decimal TotalMercadeoTotal { get; set; }
        public decimal TotalNegociosTotal { get; set; }
        public decimal TotalGeneralesTotal { get; set; }
        public decimal TotalAgenciasTotal { get; set; }
        public decimal TotalOperativosTotal { get; set; }
        public decimal RelacionActivoPromedio { get; set; }
        public Usuario oUsuario { get; set; }
        public DateTime FechaRegistro { get; set; }
    }
}
